<?php

namespace Transbank\Webpay;

use Transbank\Webpay\Options;

/**
 * Class TransaccionCompleta.
 * @var string INTEGRATION_COMMERCE_CODE
 * @var string INTEGRATION_DEFERRED_COMMERCE_CODE
 * @var string INTEGRATION_NO_CVV_COMMERCE_CODE
 * @var string INTEGRATION_DEFERRED_NO_CVV_COMMERCE_CODE
 * @var string INTEGRATION_MALL_COMMERCE_CODE
 * @var string INTEGRATION_MALL_CHILD_COMMERCE_CODE_1
 * @var string INTEGRATION_MALL_CHILD_COMMERCE_CODE_2
 * @var string INTEGRATION_MALL_NO_CVV_COMMERCE_CODE
 * @var string INTEGRATION_MALL_NO_CVV_CHILD_COMMERCE_CODE_1
 * @var string INTEGRATION_MALL_NO_CVV_CHILD_COMMERCE_CODE_2
 * @var string INTEGRATION_MALL_DEFERRED_COMMERCE_CODE
 * @var string INTEGRATION_MALL_DEFERRED_CHILD_COMMERCE_CODE_1
 * @var string INTEGRATION_MALL_DEFERRED_CHILD_COMMERCE_CODE_2
 * @var string INTEGRATION_MALL_DEFERRED_NO_CVV_COMMERCE_CODE
 * @var string INTEGRATION_MALL_DEFERRED_NO_CVV_CHILD_COMMERCE_CODE_1
 * @var string INTEGRATION_MALL_DEFERRED_NO_CVV_CHILD_COMMERCE_CODE_2
 * @var string INTEGRATION_API_KEY
 */
class TransaccionCompleta
{
    const INTEGRATION_COMMERCE_CODE = '597055555530';
    const INTEGRATION_DEFERRED_COMMERCE_CODE = '597055555531';
    const INTEGRATION_NO_CVV_COMMERCE_CODE = '597055555557';
    const INTEGRATION_DEFERRED_NO_CVV_COMMERCE_CODE = '597055555556';

    const INTEGRATION_MALL_COMMERCE_CODE = '597055555573';
    const INTEGRATION_MALL_CHILD_COMMERCE_CODE_1 = '597055555574';
    const INTEGRATION_MALL_CHILD_COMMERCE_CODE_2 = '597055555575';

    const INTEGRATION_MALL_NO_CVV_COMMERCE_CODE = '597055555551';
    const INTEGRATION_MALL_NO_CVV_CHILD_COMMERCE_CODE_1 = '597055555552';
    const INTEGRATION_MALL_NO_CVV_CHILD_COMMERCE_CODE_2 = '597055555553';

    const INTEGRATION_MALL_DEFERRED_COMMERCE_CODE = '597055555576';
    const INTEGRATION_MALL_DEFERRED_CHILD_COMMERCE_CODE_1 = '597055555577';
    const INTEGRATION_MALL_DEFERRED_CHILD_COMMERCE_CODE_2 = '597055555578';

    const INTEGRATION_MALL_DEFERRED_NO_CVV_COMMERCE_CODE = '597055555561';
    const INTEGRATION_MALL_DEFERRED_NO_CVV_CHILD_COMMERCE_CODE_1 = '597055555562';
    const INTEGRATION_MALL_DEFERRED_NO_CVV_CHILD_COMMERCE_CODE_2 = '597055555564';

    const INTEGRATION_API_KEY = Options::INTEGRATION_API_KEY;
}
