<?php

namespace Transbank\Webpay;

/**
 * Class WebpayPlus.
 * @var string INTEGRATION_COMMERCE_CODE
 * @var string INTEGRATION_DEFERRED_COMMERCE_CODE
 * @var string INTEGRATION_MALL_COMMERCE_CODE
 * @var string INTEGRATION_MALL_CHILD_COMMERCE_CODE_1
 * @var string INTEGRATION_MALL_CHILD_COMMERCE_CODE_2
 * @var string INTEGRATION_MALL_DEFERRED_COMMERCE_CODE
 * @var string INTEGRATION_MALL_DEFERRED_CHILD_COMMERCE_CODE_1
 * @var string INTEGRATION_MALL_DEFERRED_CHILD_COMMERCE_CODE_2
 * @var string INTEGRATION_API_KEY
 */
class WebpayPlus
{
    const INTEGRATION_COMMERCE_CODE = '597055555532';
    const INTEGRATION_DEFERRED_COMMERCE_CODE = '597055555540';

    const INTEGRATION_MALL_COMMERCE_CODE = '597055555535';
    const INTEGRATION_MALL_CHILD_COMMERCE_CODE_1 = '597055555536';
    const INTEGRATION_MALL_CHILD_COMMERCE_CODE_2 = '597055555537';

    const INTEGRATION_MALL_DEFERRED_COMMERCE_CODE = '597055555581';
    const INTEGRATION_MALL_DEFERRED_CHILD_COMMERCE_CODE_1 = '597055555582';
    const INTEGRATION_MALL_DEFERRED_CHILD_COMMERCE_CODE_2 = '597055555583';

    const INTEGRATION_API_KEY = Options::INTEGRATION_API_KEY;
}
