<?php

return [
    'authorize'                         => 'Transbank\Webpay\SoapClassMaps\Authorize',
    'authorizeResponse'                 => 'Transbank\Webpay\SoapClassMaps\AuthorizeResponse',
    'baseBean'                          => 'Transbank\Webpay\SoapClassMaps\BaseBean',
    'codeReverseOneClick'               => 'Transbank\Webpay\SoapClassMaps\CodeReverseOneClick',
    'codeReverseOneClickResponse'       => 'Transbank\Webpay\SoapClassMaps\CodeReverseOneClickResponse',
    'finishInscription'                 => 'Transbank\Webpay\SoapClassMaps\FinishInscription',
    'finishInscriptionResponse'         => 'Transbank\Webpay\SoapClassMaps\FinishInscriptionResponse',
    'initInscription'                   => 'Transbank\Webpay\SoapClassMaps\InitInscription',
    'initInscriptionResponse'           => 'Transbank\Webpay\SoapClassMaps\InitInscriptionResponse',
    'oneClickFinishInscriptionInput'    => 'Transbank\Webpay\SoapClassMaps\OneClickFinishInscriptionInput',
    'oneClickFinishInscriptionOutput'   => 'Transbank\Webpay\SoapClassMaps\OneClickFinishInscriptionOutput',
    'oneClickInscriptionInput'          => 'Transbank\Webpay\SoapClassMaps\OneClickInscriptionInput',
    'oneClickInscriptionOutput'         => 'Transbank\Webpay\SoapClassMaps\OneClickInscriptionOutput',
    'oneClickPayInput'                  => 'Transbank\Webpay\SoapClassMaps\OneClickPayInput',
    'oneClickPayOutput'                 => 'Transbank\Webpay\SoapClassMaps\OneClickPayOutput',
    'oneClickRemoveUserInput'           => 'Transbank\Webpay\SoapClassMaps\OneClickRemoveUserInput',
    'oneClickReverseInput'              => 'Transbank\Webpay\SoapClassMaps\OneClickReverseInput',
    'oneClickReverseOutput'             => 'Transbank\Webpay\SoapClassMaps\OneClickReverseOutput',
    'removeUser'                        => 'Transbank\Webpay\SoapClassMaps\RemoveUser',
    'removeUserResponse'                => 'Transbank\Webpay\SoapClassMaps\RemoveUserResponse',
    'reverse'                           => 'Transbank\Webpay\SoapClassMaps\Reverse',
    'reverseResponse'                   => 'Transbank\Webpay\SoapClassMaps\ReverseResponse',
];
