name: Build

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - master
      - develop
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [8.4, 8.5]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, json, curl, pcov
          coverage: pcov
      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml
      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
