name: Publish release to packagist

on:
  release:
    types:
      - published
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0

      - name: Set up PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240
        with:
          php-version: "8.4"
          tools: composer

      - name: Verify Composer installation
        run: composer --version

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Publish release to Packagist
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"repository":{"url":"https://github.com/TransbankDevelopers/transbank-sdk-php"}}' \
            "https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_API_KEY }}"
